### ISSUE TITLE
Approve / Reject fields?

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#1]
Do we we need the `Approve` / `Reject` fields in json files? If not, I think we can drop them.

**Comment by yeganehkordi** [comment]
Maybe we can drop the json files now.

**Comment by danyaljj** [comment]
Sounds good to me. If CSV files also have this column, we can retain the rows that have "yes" for "approve".

**Comment by danyaljj** [comment]
It's okay to keep it
