### ISSUE TITLE
Statistics 

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#14]
Let's collect statistics on 
 - number of tasks 
 - number of fields 
 - distribution of the field / action types

**Comment by danyaljj** [comment]
@yeganehkordi do you think we're at a stage where we can compute these?

**Comment by yeganehkordi** [comment]
We don't have all the tasks on the Turkle yet. As soon as fixing the problem with uploading them we can compute these statistics.
I think we can add a script like [test_all.py](https://github.com/allenai/natural-instructions/blob/master/src/test_all.py) that we had before, for checking if all the tasks are available on Turkle and also computing the numbers after adding or changing each task.

**Comment by danyaljj** [comment]
Yeah sounds good!

**Comment by yeganehkordi** [comment]
We can close this issue.
