### ISSUE TITLE
Change evaluation so that it receives a file?

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#19]
What do you all think @yizhongw @yeganehkordi we change [`evaluation.py`](https://github.com/JHU-CLSP/turk-instructions/blob/main/src/evaluation.py#L258) argument so that instead of task names, it receives the location of a file with task names?  Then we can have a file for test tasks and another for train tasks

**Comment by yizhongw** [comment]
Yeah I think that works better!

**Comment by yeganehkordi** [comment]
I agree, I'll fix it

**Comment by yeganehkordi** [comment]
We can close this issue.
