### ISSUE TITLE
Gold label baseline

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#21]
@yeganehkordi how difficult would it be to implement an oracle baseline that outputs the correct label for each instance?

**Comment by yeganehkordi** [comment]
It's almost the same as the evaluation class. But instead of one gold label, we may have multiple gold labels.

**Comment by danyaljj** [comment]
Right. Can we implement that? Could be our first baseline quantifying the upper-bound. 

Also, a random baseline (lower-bound).

**Comment by yeganehkordi** [comment]
Sure. 
A random baseline might be tricky as we need to generate random but acceptable responses for a webpage.

**Comment by danyaljj** [comment]
Correct. We actually need these constraints (set of acceptable responses) for other baselines too.

**Comment by danyaljj** [comment]
Although, these could be extracted from the HTML elements; right? (like, all the possible values for ratio button or checkmark).

**Comment by yeganehkordi** [comment]
I will find all the possible values for the random baseline, but do we need them for other baselines? I think they should be able to understand this from the HTML.

**Comment by danyaljj** [comment]
I think there could be a helper function that returns the possible values for a given element, if it is not text box/area. Then different baselines can make call to this helper function, if they need.

**Comment by yeganehkordi** [comment]
I have implemented this in the random baseline. I'll add this function in my next PR.
