### ISSUE TITLE
Local visualization with backend 

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#5]
Create a simple Python-based server to visualize the tasks.

Related: We may also want to look into Turkle:  https://github.com/hltcoe/turkle
It has examples (https://github.com/hltcoe/turkle/blob/master/examples/audio_transcription.html) with HTML+variables and somehow it can incorporate variables in HTML templates and visualize them.

**Comment by danyaljj** [comment]
Jinja might be helpful for visualizing the html templates + variables: 
https://stackoverflow.com/questions/8884464/python-list-and-variable-into-html-template 

Or Django: 
https://stackoverflow.com/questions/1070398/how-to-set-a-value-of-a-variable-inside-a-template-code

**Comment by yeganehkordi** [comment]
I think we can close this issue now.
