### ISSUE TITLE
`Author In-Group Analysis Phrase Classification 2` batch.csv file headers say `.on` which messes up our code 

### ISSUE THREAD

**Issue by danyaljj** [JHU-CLSP/turk-instructions#64]

**Comment by klxu03** [comment]
Not erroring, but also not passing with the right result atm when added to the list of tests

**Comment by danyaljj** [comment]
There must an error somewhere; right? If you create a PR we can go through the error log.

**Comment by klxu03** [comment]
Yeah! I just resolved this I believe throwing it back in now with the PR soon
